### ISSUE TITLE
Installation documentation unclear

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#844]
### Motivation for the feature

I found a few problems with the installation. 

1. The installation steps with conda are incomplete (pip install missing): 
    
![image](https://user-images.githubusercontent.com/2482071/124527705-3b24ba00-ddd4-11eb-9872-21338940a77d.png)

2. For "approach 2", if user wants to _not_ do the release install but instead do the git clone + `pip install -e .`, the step is presented as "optional", which is confusing:
  
![image](https://user-images.githubusercontent.com/2482071/124527813-8dfe7180-ddd4-11eb-9dcd-32d88ce98f6c.png)

I suggest rewriting the steps for the installation in a more intuitive way. @ahill187 you did an amazing job for SCT installation doc, can you please help with this?

**Comment by jcohenadad** [comment]
As I was writing this issue I noticed that @copperwiring is addressing the installation doc in #846 🚀

**Comment by copperwiring** [comment]
I would like to update that the issue will now be #847 (846 was closed due to incorrect PR). I will be working on the installation doc as I see and fix issues. @ahill187 I will probably loop you in as I attempt to fix this issue which @jcohenadad mentioned. In the meanwhile, please do share your thoughts on the documentation and what you think can make it better :)

**Comment by copperwiring** [comment]
@dyt811 There is no particular PR dedicated to it. The issues here were addressed as part of other (now closed) issue #847 in PR #847 and #851 . I wanted opinion on whether this issue is good to close?

**Comment by dyt811** [comment]
Thanks a lot for the good work. I think that has substantially been more clear the jumble of mess of instruction I wrote before that lead to Julien's original issue. Nice work. 

I still do not know what the is the best approach to address these optional components for Developers.

![image](https://user-images.githubusercontent.com/6720068/131776474-c5f22397-e365-4979-b0a3-addc3e554586.png)

Maybe eventually we should think about a dedicated section for developer or maybe tab for User vs Developer (since we will always have more user than developer?). I think that is a question worth of more discussion down the road. 

I think the current PRs meet the existing requirement acceptance criteria. 👍
